//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTCMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TTCMS.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích hoạt.
        /// </summary>
        public static string ActiveText {
            get {
                return ResourceManager.GetString("ActiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm màu sắc.
        /// </summary>
        public static string AddNewColor {
            get {
                return ResourceManager.GetString("AddNewColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm hình ảnh.
        /// </summary>
        public static string AddNewImages {
            get {
                return ResourceManager.GetString("AddNewImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm quảng cáo.
        /// </summary>
        public static string AddQCText {
            get {
                return ResourceManager.GetString("AddQCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string AddressText {
            get {
                return ResourceManager.GetString("AddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm slider.
        /// </summary>
        public static string AddSlideText {
            get {
                return ResourceManager.GetString("AddSlideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm  vào menu.
        /// </summary>
        public static string AddToMenuText {
            get {
                return ResourceManager.GetString("AddToMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi: Xảy ra ngoại lệ vui lòng liện hệ kỹ thuật!.
        /// </summary>
        public static string AlertDataCatch {
            get {
                return ResourceManager.GetString("AlertDataCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi: Dữ liệu không tồn tại hoặc đã bị xóa!.
        /// </summary>
        public static string AlertDataNull {
            get {
                return ResourceManager.GetString("AlertDataNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công: Hoàn thành xóa dữ liệu!.
        /// </summary>
        public static string AlertDataSuccess {
            get {
                return ResourceManager.GetString("AlertDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi: Không thể xóa dữ liệu hệ thống!.
        /// </summary>
        public static string AlertDataSystem {
            get {
                return ResourceManager.GetString("AlertDataSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả ngôn ngữ.
        /// </summary>
        public static string AllLanguage {
            get {
                return ResourceManager.GetString("AllLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string ApplicationURLText {
            get {
                return ResourceManager.GetString("ApplicationURLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc không?.
        /// </summary>
        public static string AreYouSureAlert {
            get {
                return ResourceManager.GetString("AreYouSureAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở trong cửa sổ mới.
        /// </summary>
        public static string blank {
            get {
                return ResourceManager.GetString("blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string BodyText {
            get {
                return ResourceManager.GetString("BodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin phiên bản.
        /// </summary>
        public static string BrowserInfo {
            get {
                return ResourceManager.GetString("BrowserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Info.
        /// </summary>
        public static string BrowserInfoText {
            get {
                return ResourceManager.GetString("BrowserInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string btnCreateSubmit {
            get {
                return ResourceManager.GetString("btnCreateSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string btnDeleteSubmit {
            get {
                return ResourceManager.GetString("btnDeleteSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm lại.
        /// </summary>
        public static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string btnUpdateSubmit {
            get {
                return ResourceManager.GetString("btnUpdateSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại danh mục.
        /// </summary>
        public static string CategoryTypeText {
            get {
                return ResourceManager.GetString("CategoryTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm danh mục sản phẩm.
        /// </summary>
        public static string CateProductCreateText {
            get {
                return ResourceManager.GetString("CateProductCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa danh mục sản phẩm.
        /// </summary>
        public static string CateProductEditText {
            get {
                return ResourceManager.GetString("CateProductEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách danh mục sản phẩm.
        /// </summary>
        public static string CateProductListText {
            get {
                return ResourceManager.GetString("CateProductListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục sản phẩm.
        /// </summary>
        public static string CateProductText {
            get {
                return ResourceManager.GetString("CateProductText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu.
        /// </summary>
        public static string ChangePasswordText {
            get {
                return ResourceManager.GetString("ChangePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kéo vào đây hoặc bấm vào để chọn avatar.
        /// </summary>
        public static string ChooseImageText {
            get {
                return ResourceManager.GetString("ChooseImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        public static string ClientNameText {
            get {
                return ResourceManager.GetString("ClientNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu sắc.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm màu.
        /// </summary>
        public static string ColorCreateText {
            get {
                return ResourceManager.GetString("ColorCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa màu.
        /// </summary>
        public static string ColorEditText {
            get {
                return ResourceManager.GetString("ColorEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách màu.
        /// </summary>
        public static string ColorListText {
            get {
                return ResourceManager.GetString("ColorListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên màu.
        /// </summary>
        public static string ColorNameText {
            get {
                return ResourceManager.GetString("ColorNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu sắc.
        /// </summary>
        public static string ColorText {
            get {
                return ResourceManager.GetString("ColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string ColseText {
            get {
                return ResourceManager.GetString("ColseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Address.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHV CMS.
        /// </summary>
        public static string CompanyText {
            get {
                return ResourceManager.GetString("CompanyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu không chính xác!.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu mới.
        /// </summary>
        public static string ConfirmPasswordNewText {
            get {
                return ResourceManager.GetString("ConfirmPasswordNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu.
        /// </summary>
        public static string ConfirmPasswordText {
            get {
                return ResourceManager.GetString("ConfirmPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa?.
        /// </summary>
        public static string ConfirmText {
            get {
                return ResourceManager.GetString("ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Contact.
        /// </summary>
        public static string contactus_setting {
            get {
                return ResourceManager.GetString("contactus_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm loại danh mục.
        /// </summary>
        public static string CreateCategoryType {
            get {
                return ResourceManager.GetString("CreateCategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo bởi.
        /// </summary>
        public static string CreatedByText {
            get {
                return ResourceManager.GetString("CreatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm chức năng.
        /// </summary>
        public static string CreateFunction {
            get {
                return ResourceManager.GetString("CreateFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo nhóm danh mục.
        /// </summary>
        public static string CreateGroupMenuText {
            get {
                return ResourceManager.GetString("CreateGroupMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo nhóm người dùng.
        /// </summary>
        public static string CreateGroupText {
            get {
                return ResourceManager.GetString("CreateGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm ngôn ngữ.
        /// </summary>
        public static string CreateLanguageText {
            get {
                return ResourceManager.GetString("CreateLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm danh mục  tin tức.
        /// </summary>
        public static string CreateNewsCateText {
            get {
                return ResourceManager.GetString("CreateNewsCateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm tin tức.
        /// </summary>
        public static string CreateNewsText {
            get {
                return ResourceManager.GetString("CreateNewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo trang.
        /// </summary>
        public static string CreatePageText {
            get {
                return ResourceManager.GetString("CreatePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới sản phẩm.
        /// </summary>
        public static string CreateProductText {
            get {
                return ResourceManager.GetString("CreateProductText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm  mới quyền.
        /// </summary>
        public static string CreateRoleText {
            get {
                return ResourceManager.GetString("CreateRoleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã màu.
        /// </summary>
        public static string CssColorText {
            get {
                return ResourceManager.GetString("CssColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn tùy chỉnh.
        /// </summary>
        public static string CustomLinksText {
            get {
                return ResourceManager.GetString("CustomLinksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mặc định.
        /// </summary>
        public static string DefaultText {
            get {
                return ResourceManager.GetString("DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa toàn bộ.
        /// </summary>
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhiều.
        /// </summary>
        public static string DeleteElement {
            get {
                return ResourceManager.GetString("DeleteElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bài viết.
        /// </summary>
        public static string DeletePost {
            get {
                return ResourceManager.GetString("DeletePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công!.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả nhóm danh mục.
        /// </summary>
        public static string DescriptionGroupMenuText {
            get {
                return ResourceManager.GetString("DescriptionGroupMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả từ khóa.
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string DetailText {
            get {
                return ResourceManager.GetString("DetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm tỉnh thành.
        /// </summary>
        public static string DistrictCreateText {
            get {
                return ResourceManager.GetString("DistrictCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa  tỉnh thành.
        /// </summary>
        public static string DistrictEditText {
            get {
                return ResourceManager.GetString("DistrictEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh  sách tỉnh thành.
        /// </summary>
        public static string DistrictListText {
            get {
                return ResourceManager.GetString("DistrictListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tỉnh thành.
        /// </summary>
        public static string DistrictNameText {
            get {
                return ResourceManager.GetString("DistrictNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh thành.
        /// </summary>
        public static string DistrictText {
            get {
                return ResourceManager.GetString("DistrictText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa loại danh mục.
        /// </summary>
        public static string EditCategoryType {
            get {
                return ResourceManager.GetString("EditCategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa chức năng.
        /// </summary>
        public static string EditFunction {
            get {
                return ResourceManager.GetString("EditFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh  sửa nhóm danh mục.
        /// </summary>
        public static string EditGroupMenuText {
            get {
                return ResourceManager.GetString("EditGroupMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa nhóm người dùng.
        /// </summary>
        public static string EditGroupUser {
            get {
                return ResourceManager.GetString("EditGroupUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa ngôn ngữ.
        /// </summary>
        public static string EditLanguageText {
            get {
                return ResourceManager.GetString("EditLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa danh mục tin tức.
        /// </summary>
        public static string EditNewsCatetext {
            get {
                return ResourceManager.GetString("EditNewsCatetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa tin.
        /// </summary>
        public static string EditNewsText {
            get {
                return ResourceManager.GetString("EditNewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa trang.
        /// </summary>
        public static string EditPageText {
            get {
                return ResourceManager.GetString("EditPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa bài viết.
        /// </summary>
        public static string EditPost {
            get {
                return ResourceManager.GetString("EditPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa bài viết theo ngôn ngữ.
        /// </summary>
        public static string EditPostByLanguage {
            get {
                return ResourceManager.GetString("EditPostByLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa tài khoản.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Account.
        /// </summary>
        public static string EmailAccount {
            get {
                return ResourceManager.GetString("EmailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email không hợp lệ!.
        /// </summary>
        public static string EmailAddressValid {
            get {
                return ResourceManager.GetString("EmailAddressValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnableSSL.
        /// </summary>
        public static string EmailEnableSSL {
            get {
                return ResourceManager.GetString("EmailEnableSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Host.
        /// </summary>
        public static string EmailHost {
            get {
                return ResourceManager.GetString("EmailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Password.
        /// </summary>
        public static string EmailPassword {
            get {
                return ResourceManager.GetString("EmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Port.
        /// </summary>
        public static string EmailPort {
            get {
                return ResourceManager.GetString("EmailPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập từ khóa tìm kiếm ....
        /// </summary>
        public static string EnterKeywordText {
            get {
                return ResourceManager.GetString("EnterKeywordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đầy đủ thông tin.
        /// </summary>
        public static string EnterYourInformationText {
            get {
                return ResourceManager.GetString("EnterYourInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi: Thêm chức năng!.
        /// </summary>
        public static string ErrorAddFunction {
            get {
                return ResourceManager.GetString("ErrorAddFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi: Ngoại lệ xảy ra, vui lòng liên hệ bộ phận kỹ thuật!.
        /// </summary>
        public static string ErrorCatch {
            get {
                return ResourceManager.GetString("ErrorCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi: Không tìm thấy dữ liệu!.
        /// </summary>
        public static string ErrorDeleteFunction {
            get {
                return ResourceManager.GetString("ErrorDeleteFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi: Chỉnh sửa chức năng!.
        /// </summary>
        public static string ErrorEditFunction {
            get {
                return ResourceManager.GetString("ErrorEditFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi: Mật khẩu cũ không chính xác!.
        /// </summary>
        public static string ErrorIncorrectOldPassword {
            get {
                return ResourceManager.GetString("ErrorIncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng..
        /// </summary>
        public static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu.
        /// </summary>
        public static string ErrorNoData {
            get {
                return ResourceManager.GetString("ErrorNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm đã tồn tại!.
        /// </summary>
        public static string ErrorRole {
            get {
                return ResourceManager.GetString("ErrorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chưa được kích hoạt!.
        /// </summary>
        public static string ErrorUserActive {
            get {
                return ResourceManager.GetString("ErrorUserActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian thao tác.
        /// </summary>
        public static string ExecutionDurationText {
            get {
                return ResourceManager.GetString("ExecutionDurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày thao tác.
        /// </summary>
        public static string ExecutionTimeText {
            get {
                return ResourceManager.GetString("ExecutionTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string FemaleText {
            get {
                return ResourceManager.GetString("FemaleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        public static string FirstNameText {
            get {
                return ResourceManager.GetString("FirstNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và Tên.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng.
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chức năng.
        /// </summary>
        public static string FunctionName {
            get {
                return ResourceManager.GetString("FunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chung.
        /// </summary>
        public static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt chung.
        /// </summary>
        public static string GeneralSettingsText {
            get {
                return ResourceManager.GetString("GeneralSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Maps.
        /// </summary>
        public static string google_map {
            get {
                return ResourceManager.GetString("google_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm danh mục.
        /// </summary>
        public static string GroupMenuText {
            get {
                return ResourceManager.GetString("GroupMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm người dùng.
        /// </summary>
        public static string GroupText {
            get {
                return ResourceManager.GetString("GroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string ImageSlide {
            get {
                return ResourceManager.GetString("ImageSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt giao diện.
        /// </summary>
        public static string InterfacesSettingText {
            get {
                return ResourceManager.GetString("InterfacesSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ IP.
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Application.
        /// </summary>
        public static string IsClosed {
            get {
                return ResourceManager.GetString("IsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện trang chủ.
        /// </summary>
        public static string IsHomeText {
            get {
                return ResourceManager.GetString("IsHomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã duy nhất.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chức năng.
        /// </summary>
        public static string KeyFunction {
            get {
                return ResourceManager.GetString("KeyFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khóa.
        /// </summary>
        public static string KeywordsText {
            get {
                return ResourceManager.GetString("KeywordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ mặc định.
        /// </summary>
        public static string LanguageDefaultText {
            get {
                return ResourceManager.GetString("LanguageDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngôn ngữ.
        /// </summary>
        public static string LanguageNameText {
            get {
                return ResourceManager.GetString("LanguageNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string LanguageTest {
            get {
                return ResourceManager.GetString("LanguageTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập cuối.
        /// </summary>
        public static string LastLoginText {
            get {
                return ResourceManager.GetString("LastLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string LastNameText {
            get {
                return ResourceManager.GetString("LastNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoạt động cuối.
        /// </summary>
        public static string LastOnline {
            get {
                return ResourceManager.GetString("LastOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài cho phép là 100.
        /// </summary>
        public static string LenghtString100 {
            get {
                return ResourceManager.GetString("LenghtString100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài cho phép là 250.
        /// </summary>
        public static string LenghtString250 {
            get {
                return ResourceManager.GetString("LenghtString250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài cho phép là 50.
        /// </summary>
        public static string LenghtString50 {
            get {
                return ResourceManager.GetString("LenghtString50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài cho phép là 500.
        /// </summary>
        public static string LenghtString500 {
            get {
                return ResourceManager.GetString("LenghtString500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn.
        /// </summary>
        public static string LinkText {
            get {
                return ResourceManager.GetString("LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Text.
        /// </summary>
        public static string LinkTextURL {
            get {
                return ResourceManager.GetString("LinkTextURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách loại danh mục.
        /// </summary>
        public static string ListCategoryType {
            get {
                return ResourceManager.GetString("ListCategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách chức năng.
        /// </summary>
        public static string ListFunction {
            get {
                return ResourceManager.GetString("ListFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhóm danh mục.
        /// </summary>
        public static string ListGroupMenuText {
            get {
                return ResourceManager.GetString("ListGroupMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhóm.
        /// </summary>
        public static string ListGroupText {
            get {
                return ResourceManager.GetString("ListGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách ngôn ngữ.
        /// </summary>
        public static string ListLanguageText {
            get {
                return ResourceManager.GetString("ListLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách lịch sử.
        /// </summary>
        public static string ListLogText {
            get {
                return ResourceManager.GetString("ListLogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tin tức.
        /// </summary>
        public static string ListNewsText {
            get {
                return ResourceManager.GetString("ListNewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách quyền.
        /// </summary>
        public static string ListRoleText {
            get {
                return ResourceManager.GetString("ListRoleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tài khoản.
        /// </summary>
        public static string ListUser {
            get {
                return ResourceManager.GetString("ListUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chi tiết.
        /// </summary>
        public static string LogDetailText {
            get {
                return ResourceManager.GetString("LogDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập vào hệ thống.
        /// </summary>
        public static string LoginToSystem {
            get {
                return ResourceManager.GetString("LoginToSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        public static string LogoutText {
            get {
                return ResourceManager.GetString("LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string MaleText {
            get {
                return ResourceManager.GetString("MaleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý menu.
        /// </summary>
        public static string ManagerMenuText {
            get {
                return ResourceManager.GetString("ManagerMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa menu.
        /// </summary>
        public static string MenuEditText {
            get {
                return ResourceManager.GetString("MenuEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string MenuItemText {
            get {
                return ResourceManager.GetString("MenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình SEO.
        /// </summary>
        public static string MetaSeo {
            get {
                return ResourceManager.GetString("MetaSeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường này  phải lớn hơn 0.
        /// </summary>
        public static string MinimumLength {
            get {
                return ResourceManager.GetString("MinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm danh mục.
        /// </summary>
        public static string NameGroupMenuText {
            get {
                return ResourceManager.GetString("NameGroupMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách danh mục tin tức.
        /// </summary>
        public static string NewsCateList {
            get {
                return ResourceManager.GetString("NewsCateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục tin tức.
        /// </summary>
        public static string NewsCateText {
            get {
                return ResourceManager.GetString("NewsCateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string NewsText {
            get {
                return ResourceManager.GetString("NewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không phải là một yêu cầu ajax.
        /// </summary>
        public static string NotAjaxRequest {
            get {
                return ResourceManager.GetString("NotAjaxRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa cập nhật!.
        /// </summary>
        public static string NoUpdates {
            get {
                return ResourceManager.GetString("NoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trong.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tùy chỉnh.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoặc.
        /// </summary>
        public static string OrText {
            get {
                return ResourceManager.GetString("OrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Footer.
        /// </summary>
        public static string PageFooter {
            get {
                return ResourceManager.GetString("PageFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách trang.
        /// </summary>
        public static string PageListText {
            get {
                return ResourceManager.GetString("PageListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        public static string pageSize {
            get {
                return ResourceManager.GetString("pageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        public static string PageText {
            get {
                return ResourceManager.GetString("PageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham số.
        /// </summary>
        public static string ParametersText {
            get {
                return ResourceManager.GetString("ParametersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài tối thiểu của mật khẩu là 6 ký tự!.
        /// </summary>
        public static string PasswordMinLong {
            get {
                return ResourceManager.GetString("PasswordMinLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string PasswordNewText {
            get {
                return ResourceManager.GetString("PasswordNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ.
        /// </summary>
        public static string PasswordOldext {
            get {
                return ResourceManager.GetString("PasswordOldext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập mật khẩu!.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string PhoneNumberText {
            get {
                return ResourceManager.GetString("PhoneNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ!.
        /// </summary>
        public static string PhoneNumberValidate {
            get {
                return ResourceManager.GetString("PhoneNumberValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng cập nhật cấu hình chung trước!.
        /// </summary>
        public static string PleaseUpdateTheGeneralConfiguration {
            get {
                return ResourceManager.GetString("PleaseUpdateTheGeneralConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm.
        /// </summary>
        public static string PointText {
            get {
                return ResourceManager.GetString("PointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí.
        /// </summary>
        public static string Possition {
            get {
                return ResourceManager.GetString("Possition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền tố.
        /// </summary>
        public static string PrefixText {
            get {
                return ResourceManager.GetString("PrefixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo sản phẩm.
        /// </summary>
        public static string ProductCreateText {
            get {
                return ResourceManager.GetString("ProductCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa sản phẩm.
        /// </summary>
        public static string ProductEditText {
            get {
                return ResourceManager.GetString("ProductEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách sản phẩm.
        /// </summary>
        public static string ProductListText {
            get {
                return ResourceManager.GetString("ProductListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán .
        /// </summary>
        public static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá khuyến mãi.
        /// </summary>
        public static string ProductPricePromotion {
            get {
                return ResourceManager.GetString("ProductPricePromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string ProductText {
            get {
                return ResourceManager.GetString("ProductText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh đại diện.
        /// </summary>
        public static string ProfilePicUrlText {
            get {
                return ResourceManager.GetString("ProfilePicUrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ.
        /// </summary>
        public static string ProfileText {
            get {
                return ResourceManager.GetString("ProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày xuất bản.
        /// </summary>
        public static string PublishedText {
            get {
                return ResourceManager.GetString("PublishedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên quảng cáo.
        /// </summary>
        public static string QCTextName {
            get {
                return ResourceManager.GetString("QCTextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoạt động gần đây.
        /// </summary>
        public static string RecentActivity {
            get {
                return ResourceManager.GetString("RecentActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết gần đây.
        /// </summary>
        public static string RecentArticles {
            get {
                return ResourceManager.GetString("RecentArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieve Email.
        /// </summary>
        public static string RecieveEmail {
            get {
                return ResourceManager.GetString("RecieveEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhớ mật khẩu.
        /// </summary>
        public static string RememberMeText {
            get {
                return ResourceManager.GetString("RememberMeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường này không được rổng!.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã quyền.
        /// </summary>
        public static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên quyền.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền.
        /// </summary>
        public static string RoleRrofile {
            get {
                return ResourceManager.GetString("RoleRrofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn nhóm.
        /// </summary>
        public static string RolesText {
            get {
                return ResourceManager.GetString("RolesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền.
        /// </summary>
        public static string RoleText {
            get {
                return ResourceManager.GetString("RoleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục cha.
        /// </summary>
        public static string RootCategory {
            get {
                return ResourceManager.GetString("RootCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tất cả.
        /// </summary>
        public static string SelectAllText {
            get {
                return ResourceManager.GetString("SelectAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở trong cửa sổ chính.
        /// </summary>
        public static string self {
            get {
                return ResourceManager.GetString("self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền.
        /// </summary>
        public static string SetRole {
            get {
                return ResourceManager.GetString("SetRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài  đặt email.
        /// </summary>
        public static string SettingEmailText {
            get {
                return ResourceManager.GetString("SettingEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt hệ thống.
        /// </summary>
        public static string SettingSystemText {
            get {
                return ResourceManager.GetString("SettingSystemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt theo.
        /// </summary>
        public static string SettingText {
            get {
                return ResourceManager.GetString("SettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string SexText {
            get {
                return ResourceManager.GetString("SexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị theo:.
        /// </summary>
        public static string ShowbyText {
            get {
                return ResourceManager.GetString("ShowbyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiển thị.
        /// </summary>
        public static string ShowName {
            get {
                return ResourceManager.GetString("ShowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        public static string ShowText {
            get {
                return ResourceManager.GetString("ShowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm kích thước.
        /// </summary>
        public static string SizeCreateText {
            get {
                return ResourceManager.GetString("SizeCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả size.
        /// </summary>
        public static string SizeDescription {
            get {
                return ResourceManager.GetString("SizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa kích  thước.
        /// </summary>
        public static string SizeEditText {
            get {
                return ResourceManager.GetString("SizeEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách kích thước.
        /// </summary>
        public static string SizeListText {
            get {
                return ResourceManager.GetString("SizeListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kích thước.
        /// </summary>
        public static string SizeNameText {
            get {
                return ResourceManager.GetString("SizeNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước.
        /// </summary>
        public static string SizeText {
            get {
                return ResourceManager.GetString("SizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên slide.
        /// </summary>
        public static string SlideTextName {
            get {
                return ResourceManager.GetString("SlideTextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        public static string SortText {
            get {
                return ResourceManager.GetString("SortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS.
        /// </summary>
        public static string StyleCSS {
            get {
                return ResourceManager.GetString("StyleCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công: Thêm chức năng!.
        /// </summary>
        public static string SuccessAddFunction {
            get {
                return ResourceManager.GetString("SuccessAddFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công: Đổi mật khẩu!.
        /// </summary>
        public static string SuccessChangePassword {
            get {
                return ResourceManager.GetString("SuccessChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thành công!.
        /// </summary>
        public static string SuccessCreate {
            get {
                return ResourceManager.GetString("SuccessCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh công: Xóa chức năng!.
        /// </summary>
        public static string SuccessDeleteFunction {
            get {
                return ResourceManager.GetString("SuccessDeleteFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công: Chỉnh sửa chức năng!.
        /// </summary>
        public static string SuccessEditFunction {
            get {
                return ResourceManager.GetString("SuccessEditFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string TagText {
            get {
                return ResourceManager.GetString("TagText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiển thị.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật bởi.
        /// </summary>
        public static string UpdatedByText {
            get {
                return ResourceManager.GetString("UpdatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật bài viết theo ngôn ngữ.
        /// </summary>
        public static string UpdatePostByLanguage {
            get {
                return ResourceManager.GetString("UpdatePostByLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công!.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết.
        /// </summary>
        public static string UrlSlide {
            get {
                return ResourceManager.GetString("UrlSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URLText {
            get {
                return ResourceManager.GetString("URLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tài khoản.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin  tài khoản.
        /// </summary>
        public static string UserProfileText {
            get {
                return ResourceManager.GetString("UserProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string UserText {
            get {
                return ResourceManager.GetString("UserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi: Trùng khóa chính!.
        /// </summary>
        public static string WarningChongqingKey {
            get {
                return ResourceManager.GetString("WarningChongqingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi: Dữ liệu không đầy đủ!.
        /// </summary>
        public static string WarningData {
            get {
                return ResourceManager.GetString("WarningData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi: Không thể xóa dữ liệu hệ thống!.
        /// </summary>
        public static string WarningDeleteFunction {
            get {
                return ResourceManager.GetString("WarningDeleteFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
